# Generated by Django 6.1.1 on 2026-09-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Đã hoàn thành'),
        ),
    ]
