# Generated by Django 6.1.1 on 2026-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_followednovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
